"""Add Phase 1 Organization Authentication Foundation

Revision ID: 0940abbefebb
Revises: b8dec86e469e
Create Date: 2026-06-13 00:25:03.690997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
from datetime import datetime, timezone
import os

# revision identifiers, used by Alembic.
revision: str = '0940abbefebb'
down_revision: Union[str, None] = 'b8dec86e469e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invitations_email'), 'admin_invitations', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user_membership')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family_id', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_family_id'), 'user_sessions', ['token_family_id'], unique=False)
    # ### end Alembic commands ###

    # --- Data Migration: Create legacy organization and backfill admins ---
    connection = op.get_bind()

    # Create Legacy Organization
    legacy_org_id = uuid.uuid4()
    now = datetime.now(timezone.utc)
    connection.execute(
        sa.text("""
            INSERT INTO organizations (id, name, slug, description, is_active, created_at, updated_at)
            VALUES (:id, :name, :slug, :description, :is_active, :created_at, :updated_at)
        """),
        {
            "id": legacy_org_id,
            "name": "EventOS Legacy Organization",
            "slug": "eventos-legacy",
            "description": "Auto-generated organization for legacy Stage-1 administrators.",
            "is_active": True,
            "created_at": now,
            "updated_at": now
        }
    )

    # Fetch existing Admins, deterministically ordered so the first row
    # (creation order, tie-broken by username) consistently becomes the owner.
    admins = connection.execute(
        sa.text("""
            SELECT a.id as admin_id, a.username, a.hashed_password, a.employee_id, e.name as employee_name
            FROM admins a
            LEFT JOIN employees e ON a.employee_id = e.employee_id
            ORDER BY a.created_at ASC, a.username ASC
        """)
    ).fetchall()

    for idx, admin_row in enumerate(admins):
        user_id = uuid.uuid4()
        # Fallback names
        first_name = admin_row.employee_name or admin_row.username
        last_name = "Legacy Admin"
        
        # We need an email for the user model. The Stage-1 admin used username.
        # We'll construct a mock email if username isn't an email.
        email = admin_row.username if "@" in admin_row.username else f"{admin_row.username}@legacy.eventos.invalid"

        connection.execute(
            sa.text("""
                INSERT INTO users (id, first_name, last_name, email, password_hash, email_verified, email_verified_at, is_active, failed_login_attempts, token_version, created_at, updated_at)
                VALUES (:id, :first_name, :last_name, :email, :password_hash, :email_verified, :email_verified_at, :is_active, :failed_login_attempts, :token_version, :created_at, :updated_at)
            """),
            {
                "id": user_id,
                "first_name": first_name,
                "last_name": last_name,
                "email": email,
                "password_hash": admin_row.hashed_password,
                "email_verified": True,
                "email_verified_at": now,
                "is_active": True,
                "failed_login_attempts": 0,
                "token_version": 1,
                "created_at": now,
                "updated_at": now
            }
        )

        # First admin (by deterministic order) becomes owner, unless an explicit
        # PRIMARY_ADMIN_USERNAME env var names a different admin as owner.
        primary_admin = os.environ.get("PHASE1_PRIMARY_ADMIN_USERNAME")
        if primary_admin:
            role = "owner" if admin_row.username == primary_admin else "admin"
        else:
            role = "owner" if idx == 0 else "admin"

        connection.execute(
            sa.text("""
                INSERT INTO organization_memberships (id, organization_id, user_id, role, status, joined_at, created_at, updated_at)
                VALUES (:id, :organization_id, :user_id, :role, :status, :joined_at, :created_at, :updated_at)
            """),
            {
                "id": uuid.uuid4(),
                "organization_id": legacy_org_id,
                "user_id": user_id,
                "role": role,
                "status": "active",
                "joined_at": now,
                "created_at": now,
                "updated_at": now
            }
        )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_token_family_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('password_reset_tokens')
    op.drop_table('organization_memberships')
    op.drop_table('email_verification_tokens')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_invitations_email'), table_name='admin_invitations')
    op.drop_table('admin_invitations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
