"""initial unified schema

Revision ID: 11b1408b448d
Revises: 
Create Date: 2026-05-23 14:13:26.420330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11b1408b448d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_recipient_email'), 'communication_logs', ['recipient_email'], unique=False)
    op.create_table('evaluators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('expertise_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_link_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluators_email'), 'evaluators', ['email'], unique=True)
    op.create_index(op.f('ix_evaluators_is_active'), 'evaluators', ['is_active'], unique=False)
    op.create_table('event_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('distribution_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_config_current_stage'), 'event_config', ['current_stage'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_is_approved'), 'teams', ['is_approved'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'evaluator_id', name='uq_evaluation_team_evaluator')
    )
    op.create_index('ix_evaluation_flagged', 'evaluations', ['is_flagged'], unique=False)
    op.create_index('ix_evaluation_team_id', 'evaluations', ['team_id', 'is_flagged'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluator_id'), 'evaluations', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_evaluations_is_flagged'), 'evaluations', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_evaluations_team_id'), 'evaluations', ['team_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=False),
    sa.Column('skill_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('welcome_email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_participant_email')
    )
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=True)
    op.create_index('ix_participants_skill_vector_gin', 'participants', ['skill_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_participants_team_id'), 'participants', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_team_id'), table_name='participants')
    op.drop_index('ix_participants_skill_vector_gin', table_name='participants', postgresql_using='gin')
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_evaluations_team_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_is_flagged'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluator_id'), table_name='evaluations')
    op.drop_index('ix_evaluation_team_id', table_name='evaluations')
    op.drop_index('ix_evaluation_flagged', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_teams_is_approved'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_event_config_current_stage'), table_name='event_config')
    op.drop_table('event_config')
    op.drop_index(op.f('ix_evaluators_is_active'), table_name='evaluators')
    op.drop_index(op.f('ix_evaluators_email'), table_name='evaluators')
    op.drop_table('evaluators')
    op.drop_index(op.f('ix_communication_logs_recipient_email'), table_name='communication_logs')
    op.drop_table('communication_logs')
    # ### end Alembic commands ###
