"""add composite indexes and fix n+1

Revision ID: 1349e9a4e212
Revises: 2a1cd1c96fff
Create Date: 2026-05-22 12:45:16.469660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1349e9a4e212'
down_revision: Union[str, None] = '2a1cd1c96fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_evaluation_flagged', 'evaluations', ['is_flagged'], unique=False)
    op.create_index('ix_evaluation_team_id', 'evaluations', ['team_id', 'is_flagged'], unique=False)
    op.drop_index('ix_participants_team_id', table_name='participants')
    op.create_index(op.f('ix_participants_team_id'), 'participants', ['team_id'], unique=False)
    op.create_unique_constraint('uq_participant_email', 'participants', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participant_email', 'participants', type_='unique')
    op.drop_index(op.f('ix_participants_team_id'), table_name='participants')
    op.create_index('ix_participants_team_id', 'participants', ['institution', 'team_id'], unique=False)
    op.drop_index('ix_evaluation_team_id', table_name='evaluations')
    op.drop_index('ix_evaluation_flagged', table_name='evaluations')
    # ### end Alembic commands ###
