"""add_notification_outbox

Revision ID: 2034bccac3df
Revises: 312223164968
Create Date: 2026-06-15 23:07:23.707435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2034bccac3df'
down_revision: Union[str, None] = '312223164968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_state', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_event_state_event_id'), 'event_state', ['event_id'], unique=False)
    op.create_foreign_key(None, 'event_state', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_inapp_event_dedupe', 'in_app_notifications', type_='unique')
    op.drop_column('in_app_notifications', 'dedupe_key')
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_outbox_pending_due', table_name='notification_outbox', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('stage_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('stage_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stage_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index('ix_outbox_pending_due', 'notification_outbox', ['available_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_outbox', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('notification_outbox', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.add_column('in_app_notifications', sa.Column('dedupe_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_inapp_event_dedupe', 'in_app_notifications', ['event_id', 'dedupe_key'])
    op.drop_constraint(None, 'event_state', type_='foreignkey')
    op.drop_index(op.f('ix_event_state_event_id'), table_name='event_state')
    op.drop_column('event_state', 'event_id')
    # ### end Alembic commands ###
