"""add composite indexes

Revision ID: 2a1cd1c96fff
Revises: cb1a56e9dc22
Create Date: 2026-05-22 06:43:03.263057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1cd1c96fff'
down_revision: Union[str, None] = 'cb1a56e9dc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_team_id', table_name='participants')
    op.create_index('ix_participants_team_id', 'participants', ['institution', 'team_id'], unique=False)
    op.create_index('ix_participants_skill_vector_gin', 'participants', ['skill_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_skill_vector_gin', table_name='participants', postgresql_using='gin')
    op.drop_index('ix_participants_team_id', table_name='participants')
    op.create_index('ix_participants_team_id', 'participants', ['team_id'], unique=False)
    # ### end Alembic commands ###
