"""add team_link_sent to participant

Revision ID: 3d068948f220
Revises: 7d2ad196fc74
Create Date: 2026-06-09 04:16:23.709069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d068948f220'
down_revision: Union[str, None] = '7d2ad196fc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('team_link_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'team_link_sent')
    # ### end Alembic commands ###
