"""add progression_confirmed to participant

Revision ID: 4b65518b48e3
Revises: 8ad905cd86d0
Create Date: 2026-06-01 18:39:11.372523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b65518b48e3'
down_revision: Union[str, None] = '8ad905cd86d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('progression_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'progression_confirmed')
    # ### end Alembic commands ###
