"""add chat models

Revision ID: 61733d2858ad
Revises: f2a3b4c5d6e7
Create Date: 2026-06-18 12:35:32.832876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61733d2858ad'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("kind IN ('team_internal', 'team_mentor')", name='ck_chat_conversation_kind'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'team_id', 'kind', name='uq_chat_conversation_team_kind')
    )
    op.create_index(op.f('ix_chat_conversations_event_id'), 'chat_conversations', ['event_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_team_id'), 'chat_conversations', ['team_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_participant_id', sa.UUID(), nullable=True),
    sa.Column('sender_mentor_id', sa.UUID(), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("sender_role IN ('participant', 'mentor')", name='ck_chat_message_sender_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_event_id'), 'chat_messages', ['event_id'], unique=False)
    op.create_index(op.f('ix_daily_updates_participant_id'), 'daily_updates', ['participant_id'], unique=False)
    op.create_index(op.f('ix_daily_updates_team_id'), 'daily_updates', ['team_id'], unique=False)
    op.alter_column('event_state', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_outbox_pending_due', table_name='notification_outbox', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('risk_signals', 'severity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_signals', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_signals', 'source',
               existing_type=sa.VARCHAR(length=80),
               server_default=None,
               existing_nullable=False)
    op.alter_column('risk_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stage_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('stage_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stage_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_risk_snapshots', 'signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'recommended_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'source',
               existing_type=sa.VARCHAR(length=80),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_risk_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'source',
               existing_type=sa.VARCHAR(length=80),
               server_default=sa.text("'phase9_risk_engine'::character varying"),
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'recommended_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('team_risk_snapshots', 'signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    op.alter_column('stage_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stage_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stage_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('risk_signals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('risk_signals', 'source',
               existing_type=sa.VARCHAR(length=80),
               server_default=sa.text("'phase9_risk_engine'::character varying"),
               existing_nullable=False)
    op.alter_column('risk_signals', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('risk_signals', 'severity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index('ix_outbox_pending_due', 'notification_outbox', ['available_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_outbox', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('notification_outbox', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('event_state', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_daily_updates_team_id'), table_name='daily_updates')
    op.drop_index(op.f('ix_daily_updates_participant_id'), table_name='daily_updates')
    op.drop_index(op.f('ix_chat_messages_event_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_conversations_team_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_event_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
