"""add phase4 stage automation

Revision ID: 673328d2ec17
Revises: 9f0a1b2c3d4e
Create Date: 2026-06-14 23:17:18.391569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '673328d2ec17'
down_revision: Union[str, None] = '9f0a1b2c3d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('in_app_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_in_app_notifications_event_id'), 'in_app_notifications', ['event_id'], unique=False)
    op.create_table('stage_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('transition_policy', sa.String(length=50), nullable=False),
    sa.Column('reminder_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'id', name='uq_stage_def_event_id'),
    sa.UniqueConstraint('event_id', 'key', name='uq_stage_def_event_key'),
    sa.UniqueConstraint('event_id', 'position', name='uq_stage_def_event_position'),
    sa.CheckConstraint('position > 0', name='ck_stage_def_position_positive'),
    sa.CheckConstraint('end_at > start_at', name='ck_stage_def_time_order'),
    sa.CheckConstraint(
        "transition_policy IN ('manual', 'automatic')",
        name='ck_stage_def_transition_policy',
    ),
    )
    op.create_index(op.f('ix_stage_definitions_event_id'), 'stage_definitions', ['event_id'], unique=False)
    op.create_table('scheduled_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_definition_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(
        ['event_id', 'stage_definition_id'],
        ['stage_definitions.event_id', 'stage_definitions.id'],
        name='fk_scheduled_action_event_stage_definition',
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.CheckConstraint(
        "action_type IN ('stage_start', 'stage_end', 'stage_warning', 'finalization_email')",
        name='ck_scheduled_action_type',
    ),
    sa.CheckConstraint(
        "status IN ('pending', 'running', 'completed', 'failed', 'cancelled')",
        name='ck_scheduled_action_status',
    )
    )
    op.create_index(op.f('ix_scheduled_actions_event_id'), 'scheduled_actions', ['event_id'], unique=False)
    op.create_table('stage_runs',
    sa.CheckConstraint(
        "status IN ('pending', 'active', 'completed', 'skipped')",
        name='ck_stage_run_status',
    ),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_definition_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(
        ['event_id', 'stage_definition_id'],
        ['stage_definitions.event_id', 'stage_definitions.id'],
        name='fk_stage_run_event_stage_definition',
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'stage_definition_id', name='uq_stage_run_event_stage')
    )
    op.create_index(op.f('ix_stage_runs_event_id'), 'stage_runs', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_runs_event_id'), table_name='stage_runs')
    op.drop_table('stage_runs')
    op.drop_index(op.f('ix_scheduled_actions_event_id'), table_name='scheduled_actions')
    op.drop_table('scheduled_actions')
    op.drop_index(op.f('ix_stage_definitions_event_id'), table_name='stage_definitions')
    op.drop_table('stage_definitions')
    op.drop_index(op.f('ix_in_app_notifications_event_id'), table_name='in_app_notifications')
    op.drop_table('in_app_notifications')
    # ### end Alembic commands ###
