"""Add admin and employee auth models

Revision ID: 6b4a1fc0ef0a
Revises: 413caf585032
Create Date: 2026-05-30 06:05:18.382371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b4a1fc0ef0a'
down_revision: Union[str, None] = '413caf585032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.drop_index('ix_admin_users_username', table_name='admin_users')
    op.drop_table('admin_users')
    op.add_column('employees', sa.Column('employee_id', sa.String(length=50), nullable=False))
    op.drop_index('ix_employees_emp_id', table_name='employees')
    op.drop_column('employees', 'emp_id')
    op.drop_column('employees', 'id')
    op.add_column('teams', sa.Column('approval_status', sa.String(length=20), server_default='pending', nullable=False))
    op.create_index(op.f('ix_teams_approval_status'), 'teams', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_approval_status'), table_name='teams')
    op.drop_column('teams', 'approval_status')
    op.add_column('employees', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('emp_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_employees_emp_id', 'employees', ['emp_id'], unique=True)
    op.drop_column('employees', 'employee_id')
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('emp_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], name='admin_users_emp_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='admin_users_pkey'),
    sa.UniqueConstraint('emp_id', name='admin_users_emp_id_key')
    )
    op.create_index('ix_admin_users_username', 'admin_users', ['username'], unique=True)
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
