"""add_template_registry

Revision ID: 6e03e770d50e
Revises: 73cd9bb51e6a
Create Date: 2026-06-14 11:58:24.581605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e03e770d50e'
down_revision: Union[str, None] = '73cd9bb51e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('default_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.add_column('events', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('template_version', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('active_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE events SET active_capabilities = '[]'::jsonb WHERE active_capabilities IS NULL")
    op.alter_column('events', 'active_capabilities', nullable=False)
    op.create_foreign_key(None, 'events', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'active_capabilities')
    
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'template_version')
    op.drop_column('events', 'template_id')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
