"""post_merge_updates

Revision ID: 73cd9bb51e6a
Revises: b862f881f870
Create Date: 2026-06-14 11:14:49.445291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73cd9bb51e6a'
down_revision: Union[str, None] = 'b862f881f870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluations', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('evaluators', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('events', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               nullable=False)
    op.alter_column('events', 'is_legacy',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_participants_email', table_name='participants')
    op.create_index(op.f('ix_participants_email'), 'participants', ['email'], unique=False)
    op.drop_constraint('uq_participant_email_event', 'participants', type_='unique')
    op.create_unique_constraint('uq_participant_email_event', 'participants', ['email'])
    op.alter_column('project_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('project_submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('project_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('uq_participant_email_event', 'participants', type_='unique')
    op.create_unique_constraint('uq_participant_email_event', 'participants', ['email', 'event_id'])
    op.drop_index(op.f('ix_participants_email'), table_name='participants')
    op.create_index('ix_participants_email', 'participants', ['email'], unique=True)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('events', 'is_legacy',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'draft'::character varying"),
               nullable=True)
    op.alter_column('events', 'configuration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'hackathon'::character varying"),
               nullable=True)
    op.alter_column('evaluators', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('evaluations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('evaluations', 'submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
