"""add rejected_teams to event_state

Revision ID: 7d2ad196fc74
Revises: b73cab0bc3de
Create Date: 2026-06-09 03:56:29.400891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d2ad196fc74'
down_revision: Union[str, None] = 'b73cab0bc3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_state', sa.Column('rejected_teams', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_state', 'rejected_teams')
    # ### end Alembic commands ###
