"""add_phase9_risk_intelligence

Revision ID: ae02a165cb83
Revises: a7c9d2e4f6b8
Create Date: 2026-06-16 08:50:14.332669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae02a165cb83'
down_revision: Union[str, None] = 'a7c9d2e4f6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_risk_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_risk_snapshots_created', 'team_risk_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_risk_snapshots_event_id'), 'team_risk_snapshots', ['event_id'], unique=False)
    op.create_index('ix_team_risk_snapshots_event_level', 'team_risk_snapshots', ['event_id', 'risk_level'], unique=False)
    op.create_index('ix_team_risk_snapshots_event_team_created', 'team_risk_snapshots', ['event_id', 'team_id', 'created_at'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('signal_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_event_id'), 'risk_signals', ['event_id'], unique=False)
    op.create_index('ix_risk_signals_event_signal', 'risk_signals', ['event_id', 'signal_type'], unique=False)
    op.create_index('ix_risk_signals_event_team', 'risk_signals', ['event_id', 'team_id'], unique=False)
    op.create_index('ix_risk_signals_observed_at', 'risk_signals', ['observed_at'], unique=False)
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_outbox_pending_due', table_name='notification_outbox', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_constraint('scheduled_actions_stage_definition_id_fkey', 'scheduled_actions', type_='foreignkey')
    op.create_foreign_key('fk_scheduled_action_event_stage_definition', 'scheduled_actions', 'stage_definitions', ['event_id', 'stage_definition_id'], ['event_id', 'id'], ondelete='CASCADE')
    op.alter_column('stage_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('stage_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('stage_runs_stage_definition_id_fkey', 'stage_runs', type_='foreignkey')
    op.create_foreign_key('fk_stage_run_event_stage_definition', 'stage_runs', 'stage_definitions', ['event_id', 'stage_definition_id'], ['event_id', 'id'], ondelete='CASCADE')
    op.alter_column('stage_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage_transitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('fk_stage_run_event_stage_definition', 'stage_runs', type_='foreignkey')
    op.create_foreign_key('stage_runs_stage_definition_id_fkey', 'stage_runs', 'stage_definitions', ['stage_definition_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stage_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stage_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('fk_scheduled_action_event_stage_definition', 'scheduled_actions', type_='foreignkey')
    op.create_foreign_key('scheduled_actions_stage_definition_id_fkey', 'scheduled_actions', 'stage_definitions', ['stage_definition_id'], ['id'])
    op.create_index('ix_outbox_pending_due', 'notification_outbox', ['available_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('notification_outbox', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notification_outbox', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('notification_outbox', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('notification_outbox', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index('ix_risk_signals_observed_at', table_name='risk_signals')
    op.drop_index('ix_risk_signals_event_team', table_name='risk_signals')
    op.drop_index('ix_risk_signals_event_signal', table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_event_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index('ix_team_risk_snapshots_event_team_created', table_name='team_risk_snapshots')
    op.drop_index('ix_team_risk_snapshots_event_level', table_name='team_risk_snapshots')
    op.drop_index(op.f('ix_team_risk_snapshots_event_id'), table_name='team_risk_snapshots')
    op.drop_index('ix_team_risk_snapshots_created', table_name='team_risk_snapshots')
    op.drop_table('team_risk_snapshots')
    # ### end Alembic commands ###
