"""Add passed_out_institution

Revision ID: b73cab0bc3de
Revises: b9076d372707
Create Date: 2026-06-03 20:09:39.624276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73cab0bc3de'
down_revision: Union[str, None] = 'b9076d372707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluators', sa.Column('passed_out_institution', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluators', 'passed_out_institution')
    # ### end Alembic commands ###
