"""add missing institution index

Revision ID: b78e6d7c093b
Revises: 1349e9a4e212
Create Date: 2026-05-22 12:54:32.971757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b78e6d7c093b'
down_revision: Union[str, None] = '1349e9a4e212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_team_id', table_name='participants')
    op.create_index('ix_participants_team_id', 'participants', ['institution', 'team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_team_id', table_name='participants')
    op.create_index('ix_participants_team_id', 'participants', ['team_id'], unique=False)
    # ### end Alembic commands ###
