"""add idempotency_key to communication_logs

Revision ID: b8dec86e469e
Revises: 3d068948f220
Create Date: 2026-06-12 20:16:21.876265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dec86e469e'
down_revision: Union[str, None] = '3d068948f220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_logs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_communication_logs_idempotency_key'), 'communication_logs', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_logs_idempotency_key'), table_name='communication_logs')
    op.drop_column('communication_logs', 'idempotency_key')
    # ### end Alembic commands ###
