"""add_event_state

Revision ID: bec64d926a87
Revises: 6b4a1fc0ef0a
Create Date: 2026-05-31 20:39:16.613254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec64d926a87'
down_revision: Union[str, None] = '6b4a1fc0ef0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('manual_override_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_state')
    # ### end Alembic commands ###
