"""add score_hash commitment to evaluations

Revision ID: f7f93f6f1c30
Revises: 39085730837b
Create Date: 2026-06-02 11:55:02.331678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f93f6f1c30'
down_revision: Union[str, None] = '39085730837b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('score_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'score_hash')
    # ### end Alembic commands ###
